### PR TITLE
Update to the top of main of NOAA-GFDL/FMS

### PR DESCRIPTION
**Pull request by MinsukJi-NOAA**
For this PR, the following tests were run:
- cpld_control_p7
- cpld_control_p7 with 32 bit dycore
- control
- control in 64 bit
- datm_cdeps_control_cfsr

Source code for tests are: /scratch2/NCEPDEV/stmp1/Minsuk.Ji/UWM_update_to_gfdl_main

### CODE REVIEW

**Review by junwang-noaa — APPROVED** [review]
I seem not seeing the conflicts in merging the code.

**Comment by MinsukJi-NOAA** [comment]
> I seem not seeing the conflicts in merging the code.

Forgot to mention that the only conflict was in diag_manager.F90. GFDL added send_data_0d_r8 and send_data_1d_r8 subroutines, which I commented out for the same reasons that were discussed in today's meeting.

**Review by binli2337 — APPROVED** [review]

**Comment by MinsukJi-NOAA** [comment]
@junwang-noaa @binli2337 Please let me know if there is anything to be done before we make a PR to NOAA-GFDL/FMS/tree/emc_mixedmode

**Comment by junwang-noaa** [comment]
Looks good, thank you!

**Pull request merged**
