### PR TITLE
Bring EMC fms_mixedmode up to date with GFDL main

### PR DESCRIPTION
**Pull request by MinsukJi-NOAA**
**Description**
Include a summary of the change and which issue is fixed. Please also include
relevant motivation and context. List any dependencies that are required for
this change.

Fixes # (issue)

**How Has This Been Tested?**
Please describe the tests that you ran to verify your changes. Please also note
any relevant details for your test configuration (e.g. compiler, OS).  Include
enough information so someone can reproduce your tests.

**Checklist:**
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] New check tests, if applicable, are included
- [ ] `make distcheck` passes

### CODE REVIEW

**Review by junwang-noaa — COMMENTED** [review]
There are a lot of changes, are there any conflicts with the mixed-mode code updates?

**Comment by MinsukJi-NOAA** [comment]
> There are a lot of changes, are there any conflicts with the mixed-mode code updates?

There were two files with conflicts: `sat_vapor_pres/sat_vapor_pres.F90` and `diag_manager/diag_manager.F90`. They were carefully resolved.

**Comment by MinsukJi-NOAA** [comment]
One of the Github Actions tests failed with this message:
```
Error: 5 Fortran file(s) contain(s) lines longer than 120 characters
./constants4/constants4.F90
./tracer_manager/tracer_manager.F90
./diag_manager/diag_manager.F90
./sat_vapor_pres/sat_vapor_pres.F90
./sat_vapor_pres/sat_vapor_pres_k.F90
```
Will fix this.

**Review by junwang-noaa — APPROVED** [review]

**Review by binli2337 — APPROVED** [review]

**Comment by MinsukJi-NOAA** [comment]
All GitHub Actions tests passed (except the one using parallelWorks) with the latest commit.

**Pull request merged**
